-- =============================================================================
-- SEED DATA: steiner_books
-- All Rudolf Steiner written works and lecture cycles from the catalog.
-- Source: rsarchive.org and steinerbooks.org (compiled March 2026)
-- =============================================================================

INSERT INTO public.steiner_books (ga_number, title, category, archive_url, steinerbooks_url, price)
VALUES
  -- -------------------------------------------------------------------------
  -- Written Works (GA 1-28)
  -- -------------------------------------------------------------------------
  ('GA 1',  'Goethean Science',                                                'philosophy',    'https://rsarchive.org/Books/GA001/', 'https://steinerbooks.org/products/9781957569321-goethean-science',                     '$24.95'),
  ('GA 2',  'Fundamentals of a Theory of Knowledge of Goethe''s Worldview',    'philosophy',    'https://rsarchive.org/Books/GA002/', 'https://steinerbooks.org/products/9780880106238-goethes-theory-of-knowledge',          '$20.00'),
  ('GA 3',  'Truth and Knowledge',                                             'philosophy',    'https://rsarchive.org/Books/GA003/', NULL,                                                                                    NULL),
  ('GA 4',  'The Philosophy of Spiritual Activity (The Philosophy of Freedom)', 'foundational',  'https://rsarchive.org/Books/GA004/', NULL,                                                                                    NULL),
  ('GA 5',  'Friedrich Nietzsche, Fighter for Freedom',                        'philosophy',    'https://rsarchive.org/Books/GA005/', NULL,                                                                                    NULL),
  ('GA 6',  'Goethe''s Conception of the World',                               'philosophy',    'https://rsarchive.org/Books/GA006/', 'https://steinerbooks.org/products/9781957569246-goethes-world-view',                   '$18.00'),
  ('GA 7',  'Mysticism at the Dawn of the Modern Age',                         'philosophy',    'https://rsarchive.org/Books/GA007/', NULL,                                                                                    NULL),
  ('GA 8',  'Christianity as Mystical Fact',                                   'christology',   'https://rsarchive.org/Books/GA008/', NULL,                                                                                    NULL),
  ('GA 9',  'Theosophy',                                                       'foundational',  'https://rsarchive.org/Books/GA009/', NULL,                                                                                    NULL),
  ('GA 10', 'How to Know Higher Worlds',                                       'foundational',  'https://rsarchive.org/Books/GA010/', NULL,                                                                                    NULL),
  ('GA 11', 'Cosmic Memory (From the Akashic Chronicle)',                      'cosmology',     'https://rsarchive.org/Books/GA011/', NULL,                                                                                    NULL),
  ('GA 12', 'The Stages of Higher Knowledge',                                  'foundational',  'https://rsarchive.org/Books/GA012/', NULL,                                                                                    NULL),
  ('GA 13', 'An Outline of Esoteric Science (Occult Science)',                 'foundational',  'https://rsarchive.org/Books/GA013/', 'https://steinerbooks.org/products/9780880104098-an-outline-of-esoteric-science',       '$19.95'),
  ('GA 14', 'Four Mystery Dramas',                                             'arts',          'https://rsarchive.org/Books/GA014/', NULL,                                                                                    NULL),
  ('GA 15', 'The Spiritual Guidance of the Individual and Humanity',           'christology',   'https://rsarchive.org/Books/GA015/', NULL,                                                                                    NULL),
  ('GA 16', 'A Road to Self-Knowledge',                                        'foundational',  'https://rsarchive.org/Books/GA016/', 'https://steinerbooks.org/products/9781732461376-a-path-to-self-knowledge',             '$45.00'),
  ('GA 17', 'The Threshold of the Spiritual World',                            'foundational',  'https://rsarchive.org/Books/GA017/', NULL,                                                                                    NULL),
  ('GA 18', 'The Riddles of Philosophy',                                       'philosophy',    'https://rsarchive.org/Books/GA018/', NULL,                                                                                    NULL),
  ('GA 19', 'Thoughts During the Time of War',                                 'social',        'https://rsarchive.org/Books/GA019/', NULL,                                                                                    NULL),
  ('GA 20', 'The Riddle of Man',                                               'philosophy',    'https://rsarchive.org/Books/GA020/', NULL,                                                                                    NULL),
  ('GA 21', 'Riddles of the Soul',                                             'philosophy',    'https://rsarchive.org/Books/GA021/', NULL,                                                                                    NULL),
  ('GA 22', 'Goethe''s Spiritual Nature',                                      'philosophy',    'https://rsarchive.org/Books/GA022/', NULL,                                                                                    NULL),
  ('GA 23', 'The Threefold Social Order (Towards Social Renewal)',             'social',        'https://rsarchive.org/Books/GA023/', NULL,                                                                                    NULL),
  ('GA 24', 'The Renewal of the Social Organism',                              'social',        'https://rsarchive.org/Books/GA024/', NULL,                                                                                    NULL),
  ('GA 25', 'Cosmology, Religion and Philosophy',                              'cosmology',     'https://rsarchive.org/Books/GA025/', NULL,                                                                                    NULL),
  ('GA 26', 'Anthroposophical Leading Thoughts',                               'foundational',  'https://rsarchive.org/Books/GA026/', 'https://steinerbooks.org/products/9781855840966-anthroposophical-leading-thoughts',    '$24.95'),
  ('GA 27', 'Fundamentals of Therapy (with Ita Wegman)',                       'medicine',      'https://rsarchive.org/Books/GA027/', NULL,                                                                                    NULL),
  ('GA 28', 'The Course of My Life (Autobiography)',                           'biography',     'https://rsarchive.org/Books/GA028/', 'https://steinerbooks.org/products/9780880106009-autobiography',                        '$29.95'),

  -- -------------------------------------------------------------------------
  -- Lecture Cycles for Sale
  -- -------------------------------------------------------------------------
  (NULL, 'A Christian Rosenkreutz Anthology',                                          'esoteric',      NULL, 'https://steinerbooks.org/products/9780893450090-a-christian-rosenkreutz-anthology',                   '$100.00'),
  (NULL, 'A Modern Art of Education',                                                  'education',     NULL, 'https://steinerbooks.org/products/9780880105118-a-modern-art-of-education',                           '$20.00'),
  (NULL, 'A Psychology of Body, Soul, and Spirit',                                     'foundational',  NULL, 'https://steinerbooks.org/products/9780880103978-a-psychology-of-body-soul-and-spirit',                '$24.95'),
  (NULL, 'A Road to Sacred Creation',                                                  'arts',          NULL, 'https://steinerbooks.org/products/9781621482611-a-road-to-sacred-creation',                           '$35.00'),
  (NULL, 'A Western Approach to Reincarnation and Karma',                              'karma',         NULL, 'https://steinerbooks.org/products/9780880103992-a-western-approach-to-reincarnation-and-karma',       '$24.95'),
  (NULL, 'According to Luke (Gospel of St. Luke)',                                     'christology',   NULL, 'https://steinerbooks.org/products/9780880104883-according-to-luke',                                   '$16.95'),
  (NULL, 'According to Matthew (Gospel of St. Matthew)',                               'christology',   NULL, 'https://steinerbooks.org/products/9780880105040-according-to-matthew',                                '$25.00'),
  (NULL, 'Agriculture (Agriculture Course)',                                           'agriculture',   NULL, 'https://steinerbooks.org/products/9781621484004-agriculture',                                         '$29.95'),
  (NULL, 'Alchemy',                                                                    'esoteric',      NULL, 'https://steinerbooks.org/products/9781855840898-alchemy',                                             '$15.95'),
  (NULL, 'An Esoteric Cosmology',                                                      'cosmology',     NULL, 'https://steinerbooks.org/products/9780880105934-an-esoteric-cosmology',                               '$18.00'),
  (NULL, 'An Exercise for Karmic Insight',                                             'karma',         NULL, 'https://steinerbooks.org/products/9781855841543-an-exercise-for-karmic-insight',                      '$6.00'),
  (NULL, 'An Introduction to Eurythmy',                                                'arts',          NULL, 'https://steinerbooks.org/products/9780880100427-an-introduction-to-eurythmy',                         '$12.00'),
  (NULL, 'An Occult Physiology',                                                       'medicine',      NULL, 'https://steinerbooks.org/products/9781855841413-an-occult-physiology',                                '$22.00'),
  (NULL, 'Ancient Myths and the New Isis Mystery',                                     'esoteric',      NULL, 'https://steinerbooks.org/products/9781621482284-ancient-myths-and-the-new-isis-mystery',              '$18.00'),
  (NULL, 'Angels',                                                                     'cosmology',     NULL, 'https://steinerbooks.org/products/9781855840607-angels',                                              '$22.00'),
  (NULL, 'Angels Speak the Foundation Stone Meditation',                               'esoteric',      NULL, 'https://steinerbooks.org/products/9781621483885-angels-speak-the-foundation-stone-meditation',        '$24.95'),
  (NULL, 'Anthroposophic Spiritual Science and Medical Therapy',                       'medicine',      NULL, 'https://steinerbooks.org/products/9781957569352-anthroposophic-spiritual-science-and-medical-therapy', '$19.95'),
  (NULL, 'Anthroposophy (A Fragment)',                                                  'foundational',  NULL, 'https://steinerbooks.org/products/9780880104012-anthroposophy-a-fragment',                            '$24.95'),
  (NULL, 'Anthroposophy and Science',                                                  'philosophy',    NULL, 'https://steinerbooks.org/products/9781957569406-anthroposophy-and-science',                           '$17.95'),
  (NULL, 'Anthroposophy and the Inner Life',                                           'foundational',  NULL, 'https://steinerbooks.org/products/9781855844179-anthroposophy-and-the-inner-life',                    '$22.00'),
  (NULL, 'Anthroposophy and the Natural Sciences',                                     'philosophy',    NULL, 'https://steinerbooks.org/products/9781621481850-anthroposophy-and-the-natural-sciences',              '$30.00'),
  (NULL, 'Anthroposophy in Everyday Life',                                             'foundational',  NULL, 'https://steinerbooks.org/products/9780880104272-anthroposophy-in-everyday-life',                      '$9.95'),
  (NULL, 'Approaching the Mystery of Golgotha',                                        'christology',   NULL, 'https://steinerbooks.org/products/9780880106061-approaching-the-mystery-of-golgotha',                '$24.95'),
  (NULL, 'Architecture as a Synthesis of the Arts',                                    'arts',          NULL, 'https://steinerbooks.org/products/9781855840577-architecture-as-a-synthesis-of-the-arts',             '$26.00'),
  (NULL, 'Architecture as Peacework',                                                  'arts',          NULL, 'https://steinerbooks.org/products/9781621480990-architecture-as-peacework',                           '$25.00'),
  (NULL, 'Architecture, Sculpture, and Painting of the First Goetheanum',              'arts',          NULL, 'https://steinerbooks.org/products/9781621482048-architecture-sculpture-and-painting-of-the-first-goetheanum', '$45.00'),
  (NULL, 'Art as Spiritual Activity',                                                  'arts',          NULL, 'https://steinerbooks.org/products/9780880103961-art-as-spiritual-activity',                           '$24.95'),
  (NULL, 'Art History as a Reflection of Inner Spiritual Impulses',                    'arts',          NULL, 'https://steinerbooks.org/products/9780880106276-art-history-as-a-reflection-of-inner-spiritual-impulses', '$45.00'),
  (NULL, 'Astronomy and Astrology',                                                    'cosmology',     NULL, 'https://steinerbooks.org/products/9781855842236-astronomy-and-astrology',                             '$26.00'),
  (NULL, 'At Home in the Universe',                                                    'cosmology',     NULL, 'https://steinerbooks.org/products/9780880104739-at-home-in-the-universe',                             '$16.00'),
  (NULL, 'Awake! For the Sake of the Future',                                          'social',        NULL, 'https://steinerbooks.org/products/9781621481058-awake-for-the-sake-of-the-future',                    '$25.00'),
  (NULL, 'Awakening to Community',                                                     'social',        NULL, 'https://steinerbooks.org/products/9780880106672-awakening-to-community',                              '$17.00'),
  (NULL, 'Background to the Gospel of St. Mark',                                       'christology',   NULL, 'https://steinerbooks.org/products/9781855846593-background-to-the-gospel-of-st-mark',                '$30.00'),
  (NULL, 'Balance in Teaching',                                                        'education',     NULL, 'https://steinerbooks.org/products/9780880105514-balance-in-teaching',                                 '$17.95'),
  (NULL, 'Becoming Fully Human',                                                       'foundational',  NULL, 'https://steinerbooks.org/products/9781621482642-becoming-fully-human',                                '$25.00'),
  (NULL, 'Bees',                                                                       'agriculture',   NULL, 'https://steinerbooks.org/products/9780880104579-bees',                                                '$25.00'),
  (NULL, 'Cosmosophy',                                                                 'cosmology',     NULL, 'https://steinerbooks.org/products/9780880101110-cosmosophy',                                          '$16.00'),
  (NULL, 'Creative Speech',                                                            'arts',          NULL, 'https://steinerbooks.org/products/9781855843868-creative-speech',                                     '$25.00'),
  (NULL, 'Daily Contemplations',                                                       'foundational',  NULL, 'https://steinerbooks.org/products/9781855845909-daily-contemplations',                                '$25.00'),
  (NULL, 'Death as Metamorphosis of Life',                                             'esoteric',      NULL, 'https://steinerbooks.org/products/9780880106078-death-as-metamorphosis-of-life',                      '$20.00'),
  (NULL, 'Deeper Secrets of Human Evolution in Light of the Gospels',                  'christology',   NULL, 'https://steinerbooks.org/products/9781855845923-deeper-secrets-of-human-evolution-in-light-of-the-gospels', '$30.00'),
  (NULL, 'Discussions with Teachers',                                                  'education',     NULL, 'https://steinerbooks.org/products/9780880104081-discussions-with-teachers',                           '$19.95'),
  (NULL, 'Disease, Karma, and Healing',                                                'medicine',      NULL, 'https://steinerbooks.org/products/9781855843837-disease-karma-and-healing',                           '$35.00'),
  (NULL, 'Dying Earth and Living Cosmos',                                              'cosmology',     NULL, 'https://steinerbooks.org/products/9781855844193-dying-earth-and-living-cosmos',                       '$37.00'),
  (NULL, 'Easter',                                                                     'christology',   NULL, 'https://steinerbooks.org/products/9781855841390-easter',                                              '$14.00'),
  (NULL, 'From Comets to Cocaine',                                                     'esoteric',      NULL, 'https://steinerbooks.org/products/9781855840881-from-comets-to-cocaine',                              '$30.00'),
  (NULL, 'From Crystals to Crocodiles',                                                'esoteric',      NULL, 'https://steinerbooks.org/products/9781855841079-from-crystals-to-crocodiles',                         '$22.00'),
  (NULL, 'From Jesus to Christ',                                                       'christology',   NULL, 'https://steinerbooks.org/products/9781855846692-from-jesus-to-christ',                                '$35.00'),
  (NULL, 'From Symptom to Reality in Modern History',                                  'social',        NULL, 'https://steinerbooks.org/products/9781855844148-from-symptom-to-reality-in-modern-history',           '$25.00'),
  (NULL, 'Fundamentals of Anthroposophical Medicine',                                  'medicine',      NULL, 'https://steinerbooks.org/products/9780936132808-fundamentals-of-anthroposophical-medicine',           '$12.95'),
  (NULL, 'Genesis',                                                                    'christology',   NULL, 'https://steinerbooks.org/products/9781855841024-genesis',                                             '$26.00')
ON CONFLICT DO NOTHING;
